package vs.hibernate.dto;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity (name = "USER_DETAILS")// entity is telling hibernate that UserDetails needs to be saved
public class UserDetails {


	@Id @GeneratedValue(strategy = GenerationType.AUTO) //this shows hibernate that userId is the autogenerated primary key
	private int userId;
	private String userName;
	@Temporal(TemporalType.DATE) 
	private Date date;
	@Embedded
	private Address address;
	@Lob 
	private String description;
	
	
	
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public Address getAddress() {
		return address;
	}
	public void setAddress(Address address) {
		this.address = address;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	
	
}
