package vs.hibernate.dto;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.JoinColumn;

import org.hibernate.annotations.CollectionId;
import org.hibernate.annotations.Type;



@Entity (name = "USER_DETAILS")// entity is telling hibernate that UserDetails needs to be saved
public class UserDetails {


	@Id @GeneratedValue(strategy = GenerationType.AUTO) //this shows hibernate that userId is the autogenerated primary key
	private int userId;
	private String userName;

	@ManyToMany (mappedBy="userdetailList")
	private Collection<Vehicle> vehicleList = new ArrayList();
	

	public Collection<Vehicle> getVehicleList() {
		return vehicleList;
	}
	public void setVehicleList(Collection<Vehicle> vehicleList) {
		this.vehicleList = vehicleList;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	//	private Date date;
//	@Lob 
//	private String description;
//	@ElementCollection
//	@JoinTable(joinColumns = @JoinColumn(name="userid"))
//	private Collection<Address> listOfAddresses = new ArrayList<Address>();
	
//	public Collection<Address> getListOfAddresses() {
//		return listOfAddresses;
//	}
//	
//	public void setListOfAddresses(Set<Address> listOfAddresses) {
//		this.listOfAddresses = listOfAddresses;
//	}
	
//	public Date getDate() {
//		return date;
//	}
//	public void setDate(Date date) {
//		this.date = date;
//	}
//	public String getDescription() {
//		return description;
//	}
//	public void setDescription(String description) {
//		this.description = description;
//	}
	
	
//	@Embedded
//	private Address homeAddress;
//	@Embedded
//	@AttributeOverrides({
//		@AttributeOverride(name="streetName",column=@Column(name="officeStreetName")),
//		@AttributeOverride(name="streetNr",column=@Column(name="officeStreetNumber")),
//		@AttributeOverride(name="city",column=@Column(name="officeCity")),
//		@AttributeOverride(name="postcode",column=@Column(name="officePostcode")),
//	})
//	private Address officeAddress;
	
//	public Address getHomeAddress() {
//		return homeAddress;
//	}
//	public void setHomeAddress(Address homeAddress) {
//		this.homeAddress = homeAddress;
//	}
//	public Address getOfficeAddress() {
//		return officeAddress;
//	}
//	public void setOfficeAddress(Address officeAddress) {
//		this.officeAddress = officeAddress;
//	}
	
	
}
